import {
  CARICATURE_SHELL_PLACEHOLDER_DESCRIPTION,
  CARICATURE_SHELL_PLACEHOLDER_HEADLINE,
  CARICATURE_SHELL_PLACEHOLDER_TAG,
  CARICATURE_LANGUAGE_OPTIONS,
} from "@/lib/caricatures/caricature-upload-metadata"

const PUBLIC_PLACEHOLDER_VALUES = new Set([
  "n/a",
  "na",
  "null",
  "none",
  "-",
  "--",
  "no text",
  "not applicable",
])

const AUTO_GENERATED_UPLOAD_HEADLINE_PATTERNS = [
  /^whatsapp\s+image\b/i,
  /^img[_\-\s]?\d+/i,
  /^dsc[_\-\s]?\d+/i,
  /^photo[_\-\s]?\d+/i,
  /^screenshot/i,
  /^snapchat/i,
  /^image\s*\(\d+\)/i,
  /^\d{8}[_\-]\d{6}/,
  /^screenshot_\d+/i,
  /^copy\s+of\s+/i,
]

export function isCaricaturePublicPlaceholderValue(value: string | null | undefined): boolean {
  const normalized = value?.trim().toLowerCase() ?? ""
  if (!normalized) return true
  return PUBLIC_PLACEHOLDER_VALUES.has(normalized)
}

export function looksLikeAutoGeneratedUploadHeadline(value: string): boolean {
  const trimmed = value.trim()
  if (!trimmed) return false
  return AUTO_GENERATED_UPLOAD_HEADLINE_PATTERNS.some((pattern) => pattern.test(trimmed))
}

export function resolvePublicCaricatureHeadline(headline: string | null | undefined): string {
  const trimmed = headline?.trim() ?? ""
  if (!trimmed) return "Untitled caricature"
  if (trimmed === CARICATURE_SHELL_PLACEHOLDER_HEADLINE) return "Untitled caricature"
  if (isCaricaturePublicPlaceholderValue(trimmed)) return "Untitled caricature"
  if (looksLikeAutoGeneratedUploadHeadline(trimmed)) return "Untitled caricature"
  return trimmed
}

export function sanitizePublicCaricatureText(value: string | null | undefined): string | null {
  const trimmed = value?.trim() ?? ""
  if (!trimmed) return null
  if (isCaricaturePublicPlaceholderValue(trimmed)) return null
  if (trimmed === CARICATURE_SHELL_PLACEHOLDER_DESCRIPTION) return null
  return trimmed
}

export function sanitizePublicCaricatureTags(values: string[] | null | undefined): string[] {
  if (!values?.length) return []
  return values
    .map((value) => value.trim())
    .filter(Boolean)
    .filter((value) => !isCaricaturePublicPlaceholderValue(value))
    .filter((value) => value !== CARICATURE_SHELL_PLACEHOLDER_TAG)
}

export function formatPublicCaricatureLanguageLabel(language: string | null | undefined): string | null {
  const normalized = language?.trim().toUpperCase() ?? ""
  if (!normalized || isCaricaturePublicPlaceholderValue(normalized)) return null
  return CARICATURE_LANGUAGE_OPTIONS.find((option) => option.value === normalized)?.label ?? titleCaseToken(normalized)
}

export function formatPublicCaricaturePublishedDate(iso: string | null | undefined): string | null {
  if (!iso?.trim()) return null
  const date = new Date(iso)
  if (Number.isNaN(date.getTime())) return null
  return new Intl.DateTimeFormat("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  }).format(date)
}

export function isRecentlyPublishedCaricature(iso: string | null | undefined, days = 14): boolean {
  if (!iso?.trim()) return false
  const publishedAt = new Date(iso)
  if (Number.isNaN(publishedAt.getTime())) return false
  const cutoff = Date.now() - days * 24 * 60 * 60 * 1000
  return publishedAt.getTime() >= cutoff
}

export function buildStaffCaricatureReviewHref(assetId: string): string {
  const params = new URLSearchParams({ status: "all", q: assetId })
  return `/staff/caricatures?${params.toString()}`
}

export interface CaricatureCardChip {
  key: string
  label: string
}

export function buildCaricatureCardChips(input: {
  categoryName: string | null | undefined
  language: string | null | undefined
  hasVisibleText: boolean | null | undefined
  hasTranslation: boolean
}): CaricatureCardChip[] {
  const chips: CaricatureCardChip[] = []

  const category = sanitizePublicCaricatureText(input.categoryName)
  if (category) chips.push({ key: "category", label: category })

  const language = formatPublicCaricatureLanguageLabel(input.language)
  if (language) chips.push({ key: "language", label: language })

  const normalizedLanguage = input.language?.trim().toUpperCase() ?? ""
  if (input.hasVisibleText === true && normalizedLanguage !== "NO_VISIBLE_TEXT") {
    chips.push({ key: "visible-text", label: "Visible text" })
  }

  if (input.hasTranslation) {
    chips.push({ key: "translation", label: "Translation available" })
  }

  return chips
}

export function buildCaricatureCardSubjectPreview(
  subjects: string[] | null | undefined,
  maxVisible = 2,
): { visible: string[]; overflowCount: number } {
  const sanitized = sanitizePublicCaricatureTags(subjects)
  if (sanitized.length <= maxVisible) {
    return { visible: sanitized, overflowCount: 0 }
  }

  return {
    visible: sanitized.slice(0, maxVisible),
    overflowCount: sanitized.length - maxVisible,
  }
}

function titleCaseToken(value: string): string {
  return value
    .split(/[_\s-]+/g)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join(" ")
}
