import assert from "node:assert/strict"
import { test } from "node:test"

import {
  formatPublicCaricatureLanguageLabel,
  formatPublicCaricaturePublishedDate,
  looksLikeAutoGeneratedUploadHeadline,
  resolvePublicCaricatureHeadline,
  sanitizePublicCaricatureText,
  buildCaricatureCardChips,
  buildCaricatureCardSubjectPreview,
} from "../src/lib/caricatures/caricature-public-display"

test("resolvePublicCaricatureHeadline hides upload filenames and placeholders", () => {
  assert.equal(resolvePublicCaricatureHeadline(""), "Untitled caricature")
  assert.equal(resolvePublicCaricatureHeadline("N/A"), "Untitled caricature")
  assert.equal(
    resolvePublicCaricatureHeadline("WhatsApp Image 2026-06-14 at 17.13.51"),
    "Untitled caricature",
  )
  assert.equal(resolvePublicCaricatureHeadline("Election satire"), "Election satire")
})

test("looksLikeAutoGeneratedUploadHeadline detects common camera and chat exports", () => {
  assert.equal(looksLikeAutoGeneratedUploadHeadline("IMG_1234"), true)
  assert.equal(looksLikeAutoGeneratedUploadHeadline("Election satire"), false)
})

test("sanitizePublicCaricatureText removes empty and placeholder values", () => {
  assert.equal(sanitizePublicCaricatureText(null), null)
  assert.equal(sanitizePublicCaricatureText("null"), null)
  assert.equal(sanitizePublicCaricatureText("Editorial description"), "Editorial description")
})

test("formatPublicCaricatureLanguageLabel maps known language codes", () => {
  assert.equal(formatPublicCaricatureLanguageLabel("MARATHI"), "Marathi")
  assert.equal(formatPublicCaricatureLanguageLabel("NO_VISIBLE_TEXT"), "No Visible Text")
  assert.equal(formatPublicCaricatureLanguageLabel(""), null)
})

test("formatPublicCaricaturePublishedDate renders readable dates", () => {
  assert.equal(formatPublicCaricaturePublishedDate("2026-06-21T10:00:00.000Z"), "21 June 2026")
})

test("buildCaricatureCardChips omits empty values and adds visible text badges", () => {
  const chips = buildCaricatureCardChips({
    categoryName: "Politics",
    language: "MARATHI",
    hasVisibleText: true,
    hasTranslation: true,
  })

  assert.deepEqual(
    chips.map((chip) => chip.label),
    ["Politics", "Marathi", "Visible text", "Translation available"],
  )
})

test("buildCaricatureCardChips uses no visible text language label without duplicate badge", () => {
  const chips = buildCaricatureCardChips({
    categoryName: "Politics",
    language: "NO_VISIBLE_TEXT",
    hasVisibleText: false,
    hasTranslation: false,
  })

  assert.deepEqual(chips.map((chip) => chip.label), ["Politics", "No Visible Text"])
})

test("buildCaricatureCardSubjectPreview limits visible subjects", () => {
  assert.deepEqual(
    buildCaricatureCardSubjectPreview(["Arshid Tiwari", "Bollywood", "Politics"], 2),
    { visible: ["Arshid Tiwari", "Bollywood"], overflowCount: 1 },
  )
})
